import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import L from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {AreaChart,ArrowUpRight,Bot,BrainCircuit,ChevronRight,CircleDollarSign,Clock3,Database,ExternalLink,Globe2,Layers3,LineChart,LockKeyhole,Menu,Search,ShieldCheck,Sparkles,Target,TrendingDown,TrendingUp,Wallet,X,Zap} from 'lucide-react';
import {assets,actions,agents} from './data';
import {RH_TESTNET,shorten,fmtUsd} from './rh';
import './styles.css';

const tabs=['Terminal','Portfolio','Agents','Markets','About'];
function App(){
 const [tab,setTab]=useState('Terminal'); const [wallet,setWallet]=useState(''); const [toast,setToast]=useState(''); const [query,setQuery]=useState(''); const [selected,setSelected]=useState(assets[0]); const [agentOpen,setAgentOpen]=useState(false); const [simulated,setSimulated]=useState(false);
 useEffect(()=>{if(!toast)return;const t=setTimeout(()=>setToast(''),2800);return()=>clearTimeout(t)},[toast]);
 const connect=async()=>{ if(window.ethereum){try{const accounts=await window.ethereum.request({method:'eth_requestAccounts'});setWallet(accounts[0]||'');setToast('Wallet connected');return}catch{}} setWallet('0x71a2…9C92');setToast('Demo wallet connected · add an EVM wallet for live mode'); };
 const filtered=useMemo(()=>assets.filter(a=>(a.symbol+a.name+a.sector).toLowerCase().includes(query.toLowerCase())),[query]);
 const nav=(n)=>setTab(n);
 return <div className="app-shell">
  <header className="topbar"><div className="topbar-inner"><button className="brand" onClick={()=>nav('Terminal')}><span className="brand-mark"><Globe2 size={17}/></span><span>ATLAS<em>RWA intelligence</em></span></button><nav>{tabs.map(t=><button key={t} onClick={()=>nav(t)} className={tab===t?'active':''}>{t}</button>)}</nav><div className="top-actions"><span className="network"><span className="live-dot"/> RH TESTNET</span><button className="wallet-btn" onClick={connect}><Wallet size={15}/>{wallet?shorten(wallet):'Connect wallet'}</button><button className="mobile-menu"><Menu size={17}/></button></div></div></header>
  {tab==='Terminal' && <Terminal assets={filtered} selected={selected} setSelected={setSelected} query={query} setQuery={setQuery} wallet={wallet} connect={connect} onAgent={()=>setAgentOpen(true)} simulated={simulated} setSimulated={setSimulated}/>} 
  {tab==='Portfolio' && <Portfolio wallet={wallet} connect={connect} simulated={simulated}/>} 
  {tab==='Agents' && <Agents onCreate={()=>setAgentOpen(true)}/>} 
  {tab==='Markets' && <Markets query={query} setQuery={setQuery}/>} 
  {tab==='About' && <About/>}
  {agentOpen&&<AgentModal close={()=>setAgentOpen(false)} toast={setToast}/>} {toast&&<div className="toast"><ShieldCheck size={15}/>{toast}</div>}
  <footer><span>ATLAS · Testnet RWA intelligence</span><span>Robinhood Chain Testnet · {RH_TESTNET.id} · <a href={RH_TESTNET.blockExplorers.default.url} target="_blank">Explorer <ExternalLink size={12}/></a></span></footer>
 </div>
}
function Terminal({assets:rows,selected,setSelected,query,setQuery,wallet,connect,onAgent,simulated,setSimulated}){
 return <main>
  <section className="hero"><div className="hero-grid"><div><div className="eyebrow"><span className="live-dot"/> ONCHAIN RWA INTELLIGENCE</div><h1>See the assets.<br/><span>Understand the risk.</span></h1><p>ATLAS turns tokenized real-world assets into a decision layer: portfolio intelligence, market data, corporate-action awareness and AI agents — built for Robinhood Chain.</p><div className="hero-actions"><button className="primary" onClick={onAgent}><Bot size={16}/> Create an RWA agent <ArrowUpRight size={14}/></button><button className="ghost" onClick={()=>document.getElementById('market-map')?.scrollIntoView({behavior:'smooth'})}>Explore assets <ChevronRight size={15}/></button></div></div><div className="hero-card"><div className="hero-card-top"><span>ATLAS SCORE</span><span className="score-chip">LIVE</span></div><div className="hero-score">76<span>/100</span></div><div className="score-bars"><Bar label="Diversification" value={72}/><Bar label="Data confidence" value={94}/><Bar label="Liquidity" value={89}/><Bar label="Concentration" value={61}/></div><div className="source-row"><Database size={13}/> Sources: wallet · onchain · market data</div></div></div></section>
  <section className="wrap"><div className="kpi-grid"><Kpi icon={<CircleDollarSign/>} label="Tracked RWA value" value={wallet?'$4,831.22':'$—'} sub={wallet?'7 assets':'Connect wallet'}/><Kpi icon={<Target/>} label="Atlas score" value="76 / 100" sub="Moderate concentration"/><Kpi icon={<Zap/>} label="Agent slots" value="1 / 3" sub="2 available"/><Kpi icon={<Clock3/>} label="Data freshness" value="15s" sub="Quote cache target"/></div>
  <div className="section-head"><div><div className="eyebrow">LIVE ASSET LAYER</div><h2>RWA market map</h2></div><div className="searchbox"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search token, sector…"/></div></div>
  <div className="terminal-grid" id="market-map"><div className="map-card"><MarketMap rows={rows} selected={selected} setSelected={setSelected}/><div className="map-caption"><span>Experimental visual layer</span><span>Map data © OpenStreetMap</span></div></div><div className="asset-panel"><div className="eyebrow">SELECTED ASSET</div><AssetDetail asset={selected}/><button className="primary wide" onClick={()=>setSimulated?.(!simulated)}>{simulated?'Simulation active':'Run scenario'} <LineChart size={15}/></button><div className="source-card"><div><ShieldCheck size={15}/> Provenance</div><span>Asset registry</span><span>Price feed / API</span><span>Wallet state</span></div></div></div>
  <div className="two-col"><section className="panel"><div className="section-head compact"><div><div className="eyebrow">ACTIVITY</div><h3>RWA data stream</h3></div><span className="status">● LIVE</span></div>{actions.map((a,i)=><div className="activity" key={i}><div className={`activity-icon ${a.tone}`}><Database size={14}/></div><div><b>{a.text}</b><small>{a.symbol} · {a.type}</small></div><time>{a.time}</time></div>)}</section><section className="panel"><div className="section-head compact"><div><div className="eyebrow">AI LAYER</div><h3>Ask ATLAS</h3></div><BrainCircuit size={18}/></div><div className="ask-box"><Sparkles size={17}/><span>“What is the biggest concentration risk?”</span><button onClick={onAgent}><ArrowUpRight size={15}/></button></div><div className="answer"><b>Portfolio concentration</b><p>AAPL represents 32.4% of the tracked portfolio. A second large technology position would increase sector concentration.</p><span>Source-backed analysis · no execution</span></div></section></div>
  <div className="disclaimer"><LockKeyhole size={15}/><div><b>Testnet & data disclaimer</b><p>ATLAS is experimental software. Testnet assets have no monetary value. Market data is informational and does not constitute investment advice. Stock Tokens are tokenized debt securities and do not grant legal or beneficial rights in the underlying securities.</p></div></div>
  </section>
 </main>
}
function Portfolio({wallet,connect,simulated}){return <main className="wrap page"><div className="eyebrow">PORTFOLIO INTELLIGENCE</div><h1>Your onchain RWA exposure.</h1><p className="lead">Connect an EVM wallet to replace the demo portfolio with live balance reads. The architecture is ready for Robinhood Chain Testnet.</p>{!wallet&&<button className="primary" onClick={connect}><Wallet size={16}/> Connect wallet</button>}<div className="portfolio-grid"><section className="panel big-panel"><div className="portfolio-total"><span>Tracked value</span><b>{wallet?'$4,831.22':'$—'}</b><small>{wallet?'Demo holdings · replace with live reads':'Wallet not connected'}</small></div><div className="allocation">{assets.slice(0,6).map(a=><div key={a.symbol}><span><i style={{background:a.color}}/>{a.symbol}</span><b>{a.weight}%</b><div className="alloc-bar"><i style={{width:`${a.weight*2.6}%`,background:a.color}}/></div></div>)}</div></section><section className="panel"><div className="eyebrow">RISK SNAPSHOT</div><div className="risk"><Bar label="Diversification" value={72}/><Bar label="Concentration" value={61}/><Bar label="Liquidity" value={89}/><Bar label="Data confidence" value={94}/></div>{simulated&&<div className="simulation"><TrendingDown size={16}/><div><b>Scenario active</b><span>+10% NVDA allocation would lower diversification by ~6 points.</span></div></div>}</section></div><section className="panel"><div className="section-head compact"><div><div className="eyebrow">HOLDINGS</div><h3>Tracked assets</h3></div><span className="status">7 ASSETS</span></div>{assets.map(a=><div className="holding" key={a.symbol}><div className="asset-logo" style={{background:a.color}}>{a.symbol[0]}</div><div><b>{a.symbol}</b><small>{a.name} · {a.sector}</small></div><strong>{fmtUsd(a.price)}</strong><span className={a.change>=0?'positive':'negative'}>{a.change>=0?'+':''}{a.change}%</span><span>{a.weight}%</span></div>)}</section></main>}
function Agents({onCreate}){return <main className="wrap page"><div className="eyebrow">AGENT LAYER</div><h1>Build agents that watch your RWA portfolio.</h1><p className="lead">ATLAS agents monitor data and explain changes. Execution stays disabled in this MVP; every insight should remain inspectable and source-backed.</p><button className="primary" onClick={onCreate}><Bot size={16}/> Create agent</button><div className="agent-grid">{agents.map(a=><div className="panel agent" key={a.name}><div className={`agent-icon ${a.color}`}><Bot size={18}/></div><div className="agent-top"><span className="tag">PUBLISHED</span><span>★ {a.rating}</span></div><h3>{a.name}</h3><p>{a.desc}</p><div className="agent-meta"><span>{a.runs} runs</span><button className="ghost">Inspect <ChevronRight size={14}/></button></div></div>)}</div><div className="panel agent-vision"><div><div className="eyebrow">NEXT</div><h3>Agent marketplace</h3><p>Creators can publish monitors, risk explainers and RWA research agents. ATLAS can later use token-gated premium runs without making financial execution the core product.</p></div><AreaChart size={60}/></div></main>}
function Markets({query,setQuery}){const rows=assets.filter(a=>(a.symbol+a.name+a.sector).toLowerCase().includes(query.toLowerCase()));return <main className="wrap page"><div className="section-head"><div><div className="eyebrow">RWA MARKET DATA</div><h1>Tokenized asset registry.</h1></div><div className="searchbox"><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets…"/></div></div><div className="panel table">{rows.map(a=><div className="market-row" key={a.symbol}><div className="asset-logo" style={{background:a.color}}>{a.symbol[0]}</div><div><b>{a.symbol}</b><small>{a.name}</small></div><span>{a.sector}</span><strong>{fmtUsd(a.price)}</strong><span className={a.change>=0?'positive':'negative'}>{a.change>=0?'+':''}{a.change}%</span><button className="icon"><ExternalLink size={14}/></button></div>)}</div><div className="source-note"><Database size={14}/><span>Production data adapter: Robinhood Stock Token API + onchain contract registry. Current browser build uses clearly labelled demo fixtures until API proxy/RPC reads are configured.</span></div></main>}
function About(){return <main className="wrap page"><div className="eyebrow">ABOUT ATLAS</div><h1>The intelligence layer for onchain RWAs.</h1><p className="lead">ATLAS is designed around a simple idea: tokenized real-world assets become more useful when their data, provenance and portfolio context are easy to understand.</p><div className="about-grid">{[['01','READ','Read wallet balances and canonical asset metadata.'],['02','PRICE','Use authoritative market data and onchain oracle infrastructure.'],['03','EXPLAIN','Turn raw RWA data into source-backed portfolio intelligence.'],['04','AGENT','Let users create monitors that watch changes over time.']].map(x=><div className="panel about-card" key={x[0]}><span>{x[0]}</span><h3>{x[1]}</h3><p>{x[2]}</p></div>)}</div><div className="disclaimer"><LockKeyhole size={15}/><div><b>Important</b><p>ATLAS does not issue or tokenize securities. It composes with existing onchain assets. Nothing in the interface is an offer, recommendation or valuation of a security. Testnet assets have no monetary value.</p></div></div></main>}
function AssetDetail({asset}){return <div className="asset-detail"><div className="asset-title"><div className="asset-logo" style={{background:asset.color}}>{asset.symbol[0]}</div><div><h3>{asset.symbol}</h3><p>{asset.name} · {asset.sector}</p></div><span className={asset.change>=0?'positive':'negative'}>{asset.change>=0?<TrendingUp size={13}/>:<TrendingDown size={13}/>} {asset.change}%</span></div><div className="asset-price">{fmtUsd(asset.price)}<small>USD quote</small></div><div className="detail-grid"><span>Portfolio weight<b>{asset.weight}%</b></span><span>Data confidence<b>94%</b></span><span>Market status<b>Active</b></span><span>Network<b>RH Testnet</b></span></div></div>}
function Bar({label,value}){return <div className="bar"><div><span>{label}</span><b>{value}</b></div><i><em style={{width:`${value}%`}}/></i></div>}
function Kpi({icon,label,value,sub}){return <div className="kpi"><span className="kpi-icon">{icon}</span><div><small>{label}</small><b>{value}</b><em>{sub}</em></div></div>}
function MarketMap({rows,selected,setSelected}){const[map,setMap]=useState(null);useEffect(()=>{const m=L.map('atlas-map',{zoomControl:false,attributionControl:true}).setView([37.7749,-122.4194],12);L.control.zoom({position:'bottomright'}).addTo(m);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:18,attribution:'© OpenStreetMap'}).addTo(m);setMap(m);setTimeout(()=>m.invalidateSize(),100);return()=>m.remove()},[]);useEffect(()=>{if(!map)return;map.eachLayer(layer=>{if(layer instanceof L.CircleMarker)map.removeLayer(layer)});rows.forEach(a=>{const p=L.circleMarker([a.lat,a.lng],{radius:selected?.symbol===a.symbol?10:7,weight:2,color:'#07100d',fillColor:a.color,fillOpacity:.95});p.bindTooltip(`<b>${a.symbol}</b><br>${a.name}<br>${a.price.toFixed(2)}`,{direction:'top'});p.on('click',()=>setSelected(a));p.addTo(map)})},[map,rows,selected]);return <div id="atlas-map"/>}
function AgentModal({close,toast}){const[name,setName]=useState('Atlas Guard');return <div className="modal-backdrop"><div className="modal"><div className="modal-head"><div><div className="eyebrow">NEW RWA AGENT</div><h3>Create monitor</h3></div><button className="icon" onClick={close}><X size={17}/></button></div><label>Agent name<input className="field" value={name} onChange={e=>setName(e.target.value)}/></label><label>Monitor<div className="checks"><span>✓ Portfolio concentration</span><span>✓ Price movement</span><span>✓ Corporate actions</span><span>✓ Data freshness</span></div></label><label>Trigger threshold<select className="field"><option>10% movement</option><option>5% movement</option><option>20% movement</option></select></label><div className="notice"><Bot size={15}/><span>Execution is disabled in this MVP. The agent only observes and explains.</span></div><button className="primary wide" onClick={()=>{close();toast(`Agent “${name}” created in demo mode`)}}>Create agent <ArrowUpRight size={14}/></button></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
