import React, { useState } from 'react';
import { SAMPLE, analyzeScenario, scenarioReport, evidenceFor, readSavedScenarios } from './research-model.js';

const usd = n => new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(n);
const KEY = 'atlas.research.scenarios.v1';
const CSS = `.research-title{max-width:850px}.research-grid{display:grid;grid-template-columns:1.3fr 1fr;gap:16px;margin:24px 0}.research-toolbar{display:flex;gap:10px;flex-wrap:wrap;margin:16px 0}.research-card h2{font-size:20px;margin:0 0 14px}.research-muted{font-size:12px;color:#99afa3;line-height:1.6}.research-row{display:grid;grid-template-columns:1.4fr 1fr .7fr auto;gap:8px;align-items:end;padding:12px 0;border-bottom:1px solid #23382c}.research-row label,.research-card>label{font-size:11px;color:#a6b7ae}.research-row .field{min-width:0;width:100%}.research-results{display:grid;grid-template-columns:1fr 1fr;gap:18px;margin:22px 0}.research-results small{display:block;color:#9aafa5}.research-results strong{display:block;font-size:26px;margin-top:6px}.research-evidence{display:grid;grid-template-columns:repeat(auto-fit,minmax(230px,1fr));gap:14px}.research-evidence dl{margin:0;font-size:12px}.research-evidence dt{color:#90a497;margin-top:14px}.research-evidence dd{margin:4px 0;overflow-wrap:anywhere}.research-evidence h3{margin:0}.research-table{width:100%;border-collapse:collapse;font-size:12px}.research-table th,.research-table td{text-align:left;padding:12px 8px;border-bottom:1px solid #23382c}.research-scroll{overflow-x:auto}.research-saved{display:flex;flex-wrap:wrap;gap:12px;align-items:center;border-top:1px solid #23382c;padding:14px 0}.research-saved span{flex:1;min-width:150px}.research-saved small{display:block;color:#91a69b}.research-bar{display:block;min-width:80px;height:6px;border-radius:8px;background:#162b20;margin-top:6px}.research-bar i{display:block;height:100%;background:#6ee7b7;border-radius:8px}.research-notice{padding:12px;border:1px solid #536234;border-radius:10px;margin-top:12px;color:#c9d9a6;font-size:12px}.research-link{color:#6ee7b7;overflow-wrap:anywhere}@media(max-width:1000px){.research-grid{grid-template-columns:1fr}}@media(max-width:600px){.research-row{grid-template-columns:1fr 1fr}.research-row label:first-child{grid-column:1/-1}.research-results strong{font-size:22px}.research-table{min-width:460px}}`;

function download(filename, text, mime = 'application/json') {
  const url = URL.createObjectURL(new Blob([text], { type: mime }));
  const link = document.createElement('a'); link.href = url; link.download = filename;
  document.body.appendChild(link); link.click(); link.remove();
  setTimeout(() => URL.revokeObjectURL(url), 1000);
}

export function StressLab() {
  const [rows, setRows] = useState(() => SAMPLE.map(a => ({ ...a })));
  const [name, setName] = useState('My RWA stress scenario');
  const [saved, setSaved] = useState(() => { try { return readSavedScenarios(localStorage); } catch { return []; } });
  const [message, setMessage] = useState('');
  let result, error;
  try { result = analyzeScenario(rows); } catch (e) { error = e.message; }
  const update = (id, key, value) => { setRows(rows.map(a => a.id === id ? { ...a, [key]: value } : a)); setMessage(''); };
  const persist = next => {
    try { localStorage.setItem(KEY, JSON.stringify(next)); setSaved(next); return true; }
    catch { setMessage('Browser storage is unavailable or full. Export your report to keep a copy.'); return false; }
  };
  const save = () => {
    if (!result || !name.trim()) { setMessage('Give your valid scenario a name first.'); return; }
    if (saved.length >= 6) { setMessage('Six scenarios are saved. Remove one before saving another.'); return; }
    if (persist([...saved, { id: crypto.randomUUID(), name: name.trim(), rows: rows.map(a => ({ ...a })), createdAt: new Date().toISOString() }])) setMessage('Scenario saved in this browser. Compare it below.');
  };
  const exportReport = format => {
    if (!result) return;
    const report = scenarioReport(name.trim() || 'Untitled scenario', rows);
    if (format === 'json') download('atlas-scenario.json', JSON.stringify(report, null, 2));
    else download('atlas-research-report.txt', ['ATLAS | HYPOTHETICAL PORTFOLIO REPORT', report.name, report.createdAt, '', ...report.assumptions, '', `Starting value: ${usd(result.before)}`, `Scenario value: ${usd(result.after)}`, `Change: ${usd(result.delta)} (${result.percent.toFixed(2)}%)`, '', ...result.assets.map(a => `${a.name}: ${usd(a.value)} -> ${usd(a.after)}; shock ${a.shock}%; weight ${a.afterWeight.toFixed(2)}%`)].join('\n'), 'text/plain');
    setMessage('Report download requested. Assumptions are included.');
  };
  return <main className="wrap page"><style>{CSS}</style><div className="eyebrow">ATLAS RESEARCH · STRESS LAB</div><h1 className="research-title">Test the portfolio.<br/>Keep the evidence.</h1><p className="lead">Build a hypothetical portfolio, apply a different price shock to each asset, and compare saved scenarios. Start without a wallet.</p>
    <div className="demo-banner"><b>HYPOTHETICAL VALUES</b><span>The starting baskets are fictional. Edited values are your assumptions, not live wallet balances or predictions.</span></div>
    <div className="research-grid"><section className="panel research-card"><h2>Build your scenario</h2><label htmlFor="research-name">Scenario name</label><input id="research-name" className="field" maxLength="80" value={name} onChange={e => setName(e.target.value)} />
    {rows.map(a => <div className="research-row" key={a.id}><label>Asset name<input aria-label={`Asset name ${a.id}`} className="field" maxLength="80" value={a.name} onChange={e => update(a.id, 'name', e.target.value)} /></label><label>Starting value ($)<input aria-label={`Starting value ${a.id}`} className="field" type="number" min="0" max="1000000000000" step="any" value={a.value} onChange={e => update(a.id, 'value', e.target.value)} /></label><label>Price change (%)<input aria-label={`Price change ${a.id}`} className="field" type="number" min="-100" max="100" step="any" value={a.shock} onChange={e => update(a.id, 'shock', e.target.value)} /></label><button className="ghost" aria-label={`Remove ${a.name}`} disabled={rows.length === 1} onClick={() => setRows(rows.filter(item => item.id !== a.id))}>Remove</button></div>)}
    <div className="research-toolbar"><button className="ghost" disabled={rows.length >= 12} onClick={() => setRows([...rows, { id: crypto.randomUUID(), name: 'Custom hypothetical asset', value: 1000, shock: 0 }])}>Add asset</button><button className="ghost" onClick={() => { setRows(SAMPLE.map(a => ({ ...a }))); setName('My RWA stress scenario'); setMessage('Sample inputs restored. Saved scenarios are unchanged.'); }}>Reset sample</button></div><p className="research-muted">Up to 12 assets. Shocks range from -100% to +100%. Fees, yields, slippage, redemptions and liquidity are excluded.</p></section>
    <section className="panel research-card" aria-live="polite"><h2>Scenario impact</h2>{error ? <p role="alert">{error}</p> : <><div className="research-results"><div><small>Starting value</small><strong>{usd(result.before)}</strong></div><div><small>Scenario value</small><strong data-testid="stress-after">{usd(result.after)}</strong></div><div><small>Change</small><strong className={result.delta < 0 ? 'negative' : 'positive'}>{usd(result.delta)}</strong><span>{result.percent.toFixed(2)}%</span></div><div><small>Largest allocation</small><strong>{result.afterConcentration === null ? 'N/A' : result.afterConcentration.toFixed(1) + '%'}</strong><span>Before: {result.concentration.toFixed(1)}%</span></div></div><div className="research-scroll"><table className="research-table"><caption>Allocation after the scenario</caption><thead><tr><th>Asset</th><th>Value</th><th>Share</th></tr></thead><tbody>{result.assets.map(a => <tr key={a.id}><th scope="row">{a.name}</th><td>{usd(a.after)}</td><td>{a.afterWeight.toFixed(1)}%<span className="research-bar"><i style={{width:`${a.afterWeight}%`}} /></span></td></tr>)}</tbody></table></div></>}
    <div className="research-toolbar"><button className="primary" disabled={!result || !name.trim()} onClick={save}>Save scenario</button><button className="ghost" disabled={!result} onClick={() => exportReport('text')}>Download report</button><button className="ghost" disabled={!result} onClick={() => exportReport('json')}>Export JSON</button></div><p role="status" className="research-muted">{message}</p></section></div>
    <section className="panel research-card"><h2>Scenario comparison</h2><p className="research-muted">Saved locally in this browser, including the original assumptions. Different starting portfolios are shown explicitly; a larger ending value alone does not indicate a better strategy.</p>{!saved.length ? <p>Save a scenario to start comparing.</p> : <><div className="research-scroll"><table className="research-table"><thead><tr><th>Scenario</th><th>Start</th><th>After</th><th>Change</th><th>Largest share</th></tr></thead><tbody>{saved.map(s => { const r = analyzeScenario(s.rows); return <tr key={s.id}><th>{s.name}</th><td>{usd(r.before)}</td><td>{usd(r.after)}</td><td>{r.percent.toFixed(2)}%</td><td>{r.afterConcentration === null ? 'N/A' : r.afterConcentration.toFixed(1)+'%'}</td></tr>; })}</tbody></table></div>{saved.map(s => <div className="research-saved" key={s.id}><span>{s.name}<small>{new Date(s.createdAt).toLocaleString()}</small></span><button className="ghost" onClick={() => { setRows(s.rows.map(a => ({ ...a }))); setName(s.name); setMessage('Saved assumptions loaded.'); }}>Load {s.name}</button><button className="ghost" onClick={() => { if (persist(saved.filter(item => item.id !== s.id))) setMessage('Saved scenario removed. Current inputs are unchanged.'); }}>Remove saved {s.name}</button></div>)}</>}</section>
  </main>;
}

export function EvidenceDesk({ assets, status }) {
  const [query, setQuery] = useState('');
  const filtered = assets.filter(a => `${a.name} ${a.symbol} ${a.contractAddress}`.toLowerCase().includes(query.toLowerCase()));
  const exportEvidence = () => download('atlas-evidence.json', JSON.stringify({ schema:'atlas.evidence.v1', exportedAt:new Date().toISOString(), network:'Robinhood Chain Testnet', chainId:46630, registryStatus:status, scope:'Filtered first-page indexer results; export time is not source update time.', verification:'ATLAS has not verified underlying assets, redemption rights or audits.', assets: filtered.map(a => ({ symbol:a.symbol, name:a.name, ...evidenceFor(a) })) }, null, 2));
  return <main className="wrap page"><style>{CSS}</style><div className="eyebrow">ATLAS RESEARCH · EVIDENCE DESK</div><h1>What does the data prove?</h1><p className="lead">Inspect what the testnet indexer supplies and what is still missing. A contract address or matching ticker is not proof of real-world backing.</p><div className="research-toolbar"><input className="field" aria-label="Search evidence" placeholder="Search name, symbol or contract" value={query} onChange={e => setQuery(e.target.value)} /><button className="ghost" disabled={!filtered.length} onClick={exportEvidence}>Export evidence report</button></div><p className="research-muted">Network: Robinhood Chain Testnet (46630). Status: {status}. Coverage: first registry page only; not a complete asset catalogue. Source freshness is not supplied. Refresh the registry from Terminal.</p>
    <div className="research-evidence">{filtered.map(a => { const e=evidenceFor(a); return <article className="panel research-card" key={a.contractAddress}><h2>{a.symbol}</h2><p className="research-muted">{a.name}</p><span className="status">INDEXED · BACKING UNVERIFIED</span><dl><dt>Contract</dt><dd>{e.contract}</dd><dt>Source</dt><dd>{e.source}</dd><dt>Price evidence</dt><dd>{e.priceAvailable ? 'Indexer exchange rate supplied; not independently verified' : 'No usable price supplied'}</dd><dt>Underlying asset</dt><dd>{e.backing}</dd><dt>Redemption rights</dt><dd>{e.redemption}</dd><dt>Audit</dt><dd>{e.audit}</dd><dt>Geography</dt><dd>{e.geographyAvailable ? 'Coordinates supplied; provenance needs review' : 'No geographic evidence supplied'}</dd></dl><a className="research-link" href={`https://explorer.testnet.chain.robinhood.com/address/${encodeURIComponent(a.contractAddress)}`} target="_blank" rel="noreferrer">Inspect contract on explorer ↗</a></article>; })}</div>{!filtered.length && <div className="panel">{status === 'syncing' ? 'Loading registry evidence…' : status === 'offline' ? 'Indexer unavailable. Retry from Terminal. No verification conclusion can be drawn.' : query ? 'No matches in the loaded registry page.' : 'No indexed assets returned.'}</div>}
  </main>;
}
